# Generated by Django 5.2.11 on 2026-03-08 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('youtube_video_id', models.CharField(max_length=32)),
                ('youtube_url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, upload_to='videos/files/')),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('download_status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('download_error_message', models.TextField(blank=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='mv_owner_created_idx'), models.Index(fields=['download_status', 'is_active'], name='mv_status_active_idx'), models.Index(fields=['youtube_video_id'], name='mv_youtube_id_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'youtube_video_id'), name='uniq_mastervideo_owner_videoid')],
            },
        ),
    ]
