# Generated by Django 5.2.11 on 2026-03-13 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mastervideo',
            name='uniq_mastervideo_owner_videoid',
        ),
        migrations.AddField(
            model_name='mastervideo',
            name='source_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('upload', 'Upload')], default='youtube', max_length=20),
        ),
        migrations.AlterField(
            model_name='mastervideo',
            name='youtube_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='mastervideo',
            name='youtube_video_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='mastervideo',
            constraint=models.UniqueConstraint(condition=models.Q(('youtube_video_id', ''), _negated=True), fields=('owner', 'youtube_video_id'), name='uniq_mastervideo_owner_videoid'),
        ),
    ]
