# Generated by Django 5.2.13 on 2026-04-22 01:48

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_mastervideo_subtitle_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastervideo',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('tech', 'Tech'), ('cook', 'Cook'), ('movie', 'Movie'), ('economic', 'Economic'), ('music', 'Music'), ('sports', 'Sports'), ('education', 'Education'), ('travel', 'Travel'), ('news', 'News'), ('gaming', 'Gaming'), ('health', 'Health'), ('other', 'Other')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='mastervideo',
            name='channel_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mastervideo',
            name='custom_thumbnail_file',
            field=models.ImageField(blank=True, upload_to=videos.models._video_thumbnail_path),
        ),
        migrations.AddField(
            model_name='mastervideo',
            name='saved_thumbnail_file',
            field=models.ImageField(blank=True, upload_to=videos.models._video_thumbnail_path),
        ),
    ]
