# Generated by Django 5.2.13 on 2026-05-02 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_dramaseriescache_dramaepisodecache'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImdbDramaSeriesCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imdb_id', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('poster_url', models.URLField(blank=True, max_length=1000)),
                ('summary', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title', 'imdb_id'],
            },
        ),
        migrations.CreateModel(
            name='ImdbDramaEpisodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season_number', models.PositiveIntegerField()),
                ('episode_number', models.PositiveIntegerField()),
                ('episode_title', models.CharField(blank=True, max_length=255)),
                ('stream_url', models.URLField(max_length=1000)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='core.imdbdramaseriescache')),
            ],
            options={
                'ordering': ['season_number', 'episode_number'],
                'unique_together': {('series', 'season_number', 'episode_number')},
            },
        ),
    ]
