# Generated by Django 5.2.13 on 2026-05-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imdbdramaseriescache_imdbdramaepisodecache'),
    ]

    operations = [
        migrations.AddField(
            model_name='imdbdramaepisodecache',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imdbdramaepisodecache',
            name='resolved_m3u8_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='imdbdramaepisodecache',
            name='subtitle_tracks',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
