# Generated by Django 5.2.11 on 2026-03-08 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipStudyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_studied_at', models.DateTimeField(blank=True, null=True)),
                ('study_count', models.PositiveIntegerField(default=0)),
                ('total_repeat_count', models.PositiveIntegerField(default=0)),
                ('total_watch_seconds', models.PositiveIntegerField(default=0)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_histories', to='clips.clip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clip_study_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'clip'), name='uniq_studyhistory_user_clip')],
            },
        ),
    ]
