# Generated by Django 5.1.15 on 2026-03-21 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0006_clip_hls_manifest_file'),
        ('dramaNlearn', '0004_thumbnailasset'),
        ('study', '0001_initial'),
        ('videos', '0004_mastervideo_subtitle_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('material_type', models.CharField(choices=[('shadowing_script', '쉐도잉 스크립트'), ('expressions', '핵심 표현 정리'), ('learning_note', '단어/문장 학습 노트')], default='shadowing_script', max_length=40)),
                ('purpose', models.CharField(choices=[('listening', '리스닝'), ('shadowing', '쉐도잉'), ('speaking', '회화'), ('vocabulary', '어휘'), ('exam', '시험 대비'), ('general', '일반 학습')], default='general', max_length=30)),
                ('difficulty', models.CharField(choices=[('beginner', '입문'), ('intermediate', '중급'), ('advanced', '고급'), ('mixed', '혼합')], default='intermediate', max_length=20)),
                ('visibility', models.CharField(choices=[('private', '비공개'), ('public', '공개')], default='private', max_length=20)),
                ('source_type', models.CharField(choices=[('clip', 'Clip'), ('master_video', 'Master Video'), ('drama_video', 'Drama Video'), ('movie', 'Movie'), ('url', 'URL'), ('manual', 'Manual')], default='manual', max_length=30)),
                ('source_title', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('imdb_code', models.CharField(blank=True, max_length=32)),
                ('generated_content', models.TextField(blank=True)),
                ('editable_notes', models.TextField(blank=True)),
                ('generation_history', models.JSONField(blank=True, default=list)),
                ('copied_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='study.studymaterial')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to=settings.AUTH_USER_MODEL)),
                ('source_clip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_materials', to='clips.clip')),
                ('source_drama_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_materials', to='dramaNlearn.video')),
                ('source_master_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_materials', to='videos.mastervideo')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyMaterialGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_key', models.CharField(max_length=40)),
                ('prompt_intent', models.CharField(blank=True, max_length=255)),
                ('input_snapshot', models.JSONField(blank=True, default=dict)),
                ('output_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_material_generations', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='study.studymaterial')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['owner', '-updated_at'], name='studymat_owner_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['material_type', 'visibility'], name='studymat_type_visibility_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['source_type', '-created_at'], name='studymat_source_created_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterialgeneration',
            index=models.Index(fields=['material', '-created_at'], name='smgen_mat_created_idx'),
        ),
    ]
