# Generated by Django 5.2.11 on 2026-03-08 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time_seconds', models.PositiveIntegerField()),
                ('end_time_seconds', models.PositiveIntegerField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('clip_file', models.FileField(blank=True, upload_to='clips/files/')),
                ('thumbnail_file', models.ImageField(blank=True, upload_to='clips/thumbnails/')),
                ('is_public', models.BooleanField(default=False)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('extraction_error_message', models.TextField(blank=True)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('last_studied_at_cache', models.DateTimeField(blank=True, null=True)),
                ('study_count_cache', models.PositiveIntegerField(default=0)),
                ('like_count_cache', models.PositiveIntegerField(default=0)),
                ('comment_count_cache', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('master_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='videos.mastervideo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='clip_owner_created_idx'), models.Index(fields=['is_public', 'is_active'], name='clip_public_active_idx'), models.Index(fields=['extraction_status'], name='clip_extract_status_idx')],
            },
        ),
    ]
