# Generated by Django 5.2.11 on 2026-03-08 23:22

import clips.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_directory_label', models.CharField(blank=True, max_length=255)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('success_files', models.PositiveIntegerField(default=0)),
                ('failed_files', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial_failed', 'Partial Failed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='clip',
            name='clip_extract_status_idx',
        ),
        migrations.AddField(
            model_name='clip',
            name='file_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clip',
            name='file_size_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clip',
            name='file_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='clip',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clip',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clip',
            name='source_type',
            field=models.CharField(choices=[('extracted', 'Extracted'), ('uploaded', 'Uploaded')], default='extracted', max_length=20),
        ),
        migrations.AlterField(
            model_name='clip',
            name='clip_file',
            field=models.FileField(blank=True, upload_to=clips.models._uploaded_clip_path),
        ),
        migrations.AlterField(
            model_name='clip',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clip',
            name='end_time_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clip',
            name='master_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='videos.mastervideo'),
        ),
        migrations.AlterField(
            model_name='clip',
            name='start_time_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clipuploadbatch',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clip_upload_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clip',
            name='upload_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clips', to='clips.clipuploadbatch'),
        ),
        migrations.AddIndex(
            model_name='clip',
            index=models.Index(fields=['file_status'], name='clip_file_status_idx'),
        ),
        migrations.AddIndex(
            model_name='clip',
            index=models.Index(fields=['source_type', '-created_at'], name='clip_source_created_idx'),
        ),
        migrations.AddIndex(
            model_name='clipuploadbatch',
            index=models.Index(fields=['owner', '-created_at'], name='clipbatch_owner_created_idx'),
        ),
        migrations.AddIndex(
            model_name='clipuploadbatch',
            index=models.Index(fields=['status', '-created_at'], name='clipbatch_status_created_idx'),
        ),
    ]
