# Generated by Django 5.2.11 on 2026-03-13 22:19

import clips.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0002_clipuploadbatch_remove_clip_clip_extract_status_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='thumbnail_file',
            field=models.ImageField(blank=True, upload_to=clips.models._clip_thumbnail_path),
        ),
    ]
