# Generated by Django 5.1.15 on 2026-04-21 23:08

import clips.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0006_clip_hls_manifest_file'),
        ('videos', '0004_mastervideo_subtitle_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to=clips.models._clip_image_path)),
                ('seq_no', models.PositiveIntegerField(default=1)),
                ('capture_time_seconds', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clips.clip')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clip_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['seq_no', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to=clips.models._album_image_path)),
                ('source', models.CharField(choices=[('capture', 'Capture'), ('thumbnail', 'Thumbnail'), ('upload', 'Upload')], default='upload', max_length=20)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('clip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_images', to='clips.clip')),
                ('master_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_images', to='videos.mastervideo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_images', to=settings.AUTH_USER_MODEL)),
                ('clip_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_refs', to='clips.clipimage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clipimage',
            index=models.Index(fields=['owner', '-created_at'], name='clipimage_owner_created_idx'),
        ),
        migrations.AddIndex(
            model_name='clipimage',
            index=models.Index(fields=['clip', 'seq_no'], name='clipimage_clip_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='albumimage',
            index=models.Index(fields=['owner', '-created_at'], name='albumimage_owner_created_idx'),
        ),
        migrations.AddIndex(
            model_name='albumimage',
            index=models.Index(fields=['source', '-created_at'], name='albumimage_source_created_idx'),
        ),
    ]
