# Generated by Django 5.2.13 on 2026-04-22 01:48

import clips.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0007_clipimage_albumimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='custom_thumbnail_file',
            field=models.ImageField(blank=True, upload_to=clips.models._clip_custom_thumbnail_path),
        ),
    ]
