from django.urls import path
from django.views.generic import RedirectView

from .views import (
    AlbumImageDeleteView,
    AlbumImageDetailView,
    AlbumImageUpdateView,
    AlbumUploadView,
    ClipBulkUploadView,
    ClipCreateAjaxView,
    ClipCreateView,
    ClipDeleteView,
    ClipDetailView,
    ClipDownloadView,
    ClipImageCaptureView,
    ClipImageDeleteView,
    ClipImageEditView,
    ClipMetadataUpdateView,
    ClipRetryView,
    ClipStatusApiView,
    ClipSubtitleExtractView,
    ClipSubtitleSaveView,
    ClipThumbnailProxyView,
    ClipUpdateApiView,
    MasterVideoSubtitleTrackView,
    ClipUpdateView,
    ClipUploadBatchDetailView,
    ClipUploadBatchListView,
)

app_name = "clips"

urlpatterns = [
    path("", RedirectView.as_view(pattern_name="dashboard:home", permanent=False), name="list"),
    path("album/", RedirectView.as_view(pattern_name="dashboard:home", permanent=False), name="album-list"),
    path("album/upload/", AlbumUploadView.as_view(), name="album-upload"),
    path("album/<int:pk>/", AlbumImageDetailView.as_view(), name="album-detail"),
    path("album/<int:pk>/update/", AlbumImageUpdateView.as_view(), name="album-update"),
    path("album/<int:pk>/delete/", AlbumImageDeleteView.as_view(), name="album-delete"),
    path("create/", ClipCreateView.as_view(), name="create"),
    path("master-video/<int:video_id>/subtitle.vtt", MasterVideoSubtitleTrackView.as_view(), name="master-video-subtitle-vtt"),
    path("bulk-upload/", ClipBulkUploadView.as_view(), name="bulk-upload"),
    path("batches/", ClipUploadBatchListView.as_view(), name="batch-list"),
    path("batches/<int:pk>/", ClipUploadBatchDetailView.as_view(), name="batch-detail"),
    path("images/<int:pk>/edit/", ClipImageEditView.as_view(), name="image-edit"),
    path("images/<int:pk>/delete/", ClipImageDeleteView.as_view(), name="image-delete"),
    path("api/create-clip/", ClipCreateAjaxView.as_view(), name="api-create"),
    path("api/clip-status/<int:pk>/", ClipStatusApiView.as_view(), name="api-status"),
    path("api/clip/<int:pk>/update/", ClipUpdateApiView.as_view(), name="api-update"),
    path("api/clip/<int:pk>/proxy-thumb/", ClipThumbnailProxyView.as_view(), name="thumb-proxy"),
    path("<int:pk>/", ClipDetailView.as_view(), name="detail"),
    path("<int:pk>/capture-image/", ClipImageCaptureView.as_view(), name="image-capture"),
    path("<int:pk>/download/", ClipDownloadView.as_view(), name="download"),
    path("<int:pk>/metadata/", ClipMetadataUpdateView.as_view(), name="metadata-update"),
    path("<int:pk>/subtitle-extract/", ClipSubtitleExtractView.as_view(), name="subtitle-extract"),
    path("<int:pk>/subtitle-save/", ClipSubtitleSaveView.as_view(), name="subtitle-save"),
    path("<int:pk>/edit/", ClipUpdateView.as_view(), name="edit"),
    path("<int:pk>/delete/", ClipDeleteView.as_view(), name="delete"),
    path("<int:pk>/retry/", ClipRetryView.as_view(), name="retry"),
]
