# Generated by Django 5.2.11 on 2026-03-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('source_url', models.URLField(max_length=1000, verbose_name='send2video URL')),
                ('player_url', models.URLField(blank=True, max_length=1000, verbose_name='플레이어 iframe URL')),
                ('m3u8_url', models.TextField(blank=True, verbose_name='m3u8 스트리밍 URL')),
                ('thumbnail', models.URLField(blank=True, max_length=1000, verbose_name='썸네일')),
                ('duration', models.FloatField(default=0, verbose_name='재생시간(초)')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('fetching', '추출중'), ('ready', '재생가능'), ('error', '오류'), ('expired', '만료됨')], default='pending', max_length=20)),
                ('error_msg', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '동영상',
                'verbose_name_plural': '동영상 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
