# Generated by Django 5.2.11 on 2026-03-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dramaNlearn", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subtitle_tracks',
            field=models.TextField(blank=True, default='[]', verbose_name='자막 트랙 JSON'),
        ),
    ]
