# Generated by Django 5.2.11 on 2026-03-14 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import dramaNlearn.models


class Migration(migrations.Migration):

    dependencies = [
        ("dramaNlearn", "0003_video_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ThumbnailAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, verbose_name="이름")),
                ("image", models.ImageField(upload_to=dramaNlearn.models.thumbnail_asset_upload_path, verbose_name="이미지")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="thumbnail_assets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록 사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "썸네일 자산",
                "verbose_name_plural": "썸네일 자산",
                "ordering": ["name", "-created_at"],
            },
        ),
    ]
