# Generated by Django 5.2 on 2025-12-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_saver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('video_title', models.CharField(blank=True, max_length=255)),
                ('chapter_index', models.PositiveIntegerField()),
                ('chapter_title', models.CharField(max_length=255)),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('output_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('failed', 'failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
