# Generated by Django 6.0.2 on 2026-02-22 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_saver', '0002_chapterdownload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'ordering': ['-created_at']},
        ),
    ]
