# Generated by Django 5.2.14 on 2026-06-06 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=200, unique=True)),
                ('search_count', models.IntegerField(default=1)),
                ('last_searched', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '영화 검색어',
                'verbose_name_plural': '영화 검색어 목록',
                'ordering': ['-last_searched'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('official', 'YTS-Official'), ('api', 'YTS-API'), ('tmdb', 'TMDB')], max_length=20)),
                ('url', models.URLField(max_length=1000)),
                ('thumbnail', models.URLField(blank=True, max_length=1000, null=True)),
                ('large_cover', models.URLField(blank=True, max_length=1000, null=True)),
                ('imdb_code', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('tmdb_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True, null=True)),
                ('torrents', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movies.searchquery')),
            ],
            options={
                'ordering': ['-year', 'title'],
                'indexes': [models.Index(fields=['title', 'year'], name='movies_movi_title_abbe27_idx'), models.Index(fields=['imdb_code'], name='movies_movi_imdb_co_713aa0_idx'), models.Index(fields=['tmdb_id'], name='movies_movi_tmdb_id_0e4cad_idx')],
                'unique_together': {('title', 'year', 'source', 'search_query')},
            },
        ),
    ]
