# Generated by Django 5.2.11 on 2026-03-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='job_type',
            field=models.CharField(choices=[('youtube_download', 'YouTube Download'), ('clip_extraction', 'Clip Extraction'), ('clip_batch_upload', 'Clip Batch Upload'), ('clip_file_postprocess', 'Clip File Postprocess')], max_length=100),
        ),
    ]
