# Generated by Django 5.1.15 on 2026-04-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_alter_backgroundjob_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundjob',
            name='job_type',
            field=models.CharField(choices=[('youtube_download', 'Source Video Import'), ('master_video_upload_process', 'Master Video Upload Process'), ('clip_extraction', 'Clip Extraction'), ('clip_batch_upload', 'Clip Batch Upload'), ('clip_file_postprocess', 'Clip File Postprocess'), ('drama_video_extract', 'Drama Video Extract')], max_length=100),
        ),
    ]
